### ISSUE TITLE
JavaScript Dependencies

### ISSUE THREAD

**Issue by davidtaylorhq** [nottinghamtec/PyRIGS#215]
Are currently a mess. This looks like a pretty tidy, and low effort way to fix it:

https://github.com/nvbn/django-bower

**Comment by tomtom5152** [comment]
Having stumbled across this myself I found it a little bit temperamental at best, and resorted to using npm and bower using ember (which I know is full on effort to setup with this, but overall would look something like `ember install && ember build`).

For Heroku this would potentially mean adding the [node.js buildback](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-nodejs) as a [secondary buildpack](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app)

As I've fallen in love with ember, when I get fed up with the project I'm working on (because it is incredibly complex and makes my head hurt), I'll have a go at replacing interaction.js with an ember app, thereby tidying up all the JS dependencies in one go.

**Comment by davidtaylorhq** [comment]
My only reservation with this is that it adds another complexity for developers (having to install a node server)... Maybe if we make a working dockerfile then that would be ok

**Comment by tomtom5152** [comment]
I think vagrant is generally seen as better than docker for development because the change are reflected in real time whereas docker requires a rebuild (which downloads all of the requirements again every time).

From today's experiments I have replicated the "Add X" functionality of the new rig page in my other ember project in an afternoon, and it is much nice code based around callbacks rather than bindings.

**Comment by tomtom5152** [comment]
To revist this (my god was that a year ago), I now believe a simple setup of yarn to install dependencies and gulp to build/concat/minify to the static directory so Django can process it would be the most appropriate way to go.

**Comment by davidtaylorhq** [comment]
>simple

Really? Is it though? 😆

**Comment by tomtom5152** [comment]
It's simpler than the current ruby based compass bodge that happens.

**Comment by FreneticScribbler** [comment]
Nothing is ever simple... :face_with_head_bandage:
