### ISSUE TITLE
External accounts 

### ISSUE THREAD

**Issue by tomtom5152** [nottinghamtec/PyRIGS#274]
TEC has external accounts on third party accounting systems (such as the uni agresso), and it's becoming evident that the uni is incapable of dealing with the fact that the name on it is UoNSU so maybe we should start putting something along the lines of "Our reference with you: 12345" based on the organisation onto invoices.

**Comment by davidtaylorhq** [comment]
@tomtom5152 Problem is how do we know what clients have university accounts

**Comment by tomtom5152** [comment]
@davidtaylorhq It would require a short conversation of "please sign this form" "Oh were already I'm agresso, here's our number" *update RIGS for future reference*

**Comment by davidtaylorhq** [comment]
@tomtom5152 In an ideal world, I agree. However in the real world I don't think that conversation will ever happen - they'll just skip straight to getting confused. I think we should just put 

"Clients with UoN Agresso accounts should create a purchase order. Our number is 1234 (UoNSU)"

**Comment by tomtom5152** [comment]
My issue with that is it shows to the world that treasury and the uni finance office are blithering idiots. Whilst this may be common knowledge to regular clients, do we really want to show just how incompetent they are to say BAE or similar when trying to book a job?

I think the confusion would happen the first time yes, at which point the problem is fixed for the future.

**Comment by davidtaylorhq** [comment]
@tomtom5152 That's a fair point. So would you add another Boolean to the organisation model "Client has UoN account"?
Or we could change the current field to a multiple choice "Account Type" with options "UoNSU", "UoN", "External"

**Comment by tomtom5152** [comment]
That was my other thought, but having a text box makes it open to external clients who need some help such as the council etc.

**Comment by davidtaylorhq** [comment]
@tomtom5152 Ah I see, although by having a free text field you open it up to user incompetence (spelling mistakes etc.)

**Comment by tomtom5152** [comment]
Alternatively, we could just pressure treasury to fill out the supplier from again to get TEC listed separately in agresso which would make this irrelevant

**Comment by samozzy** [comment]
> Alternatively, we could just pressure treasury to fill out the supplier from again to get TEC listed separately in agresso which would make this irrelevant

Was this a thing in the past?

It's mostly university accounts that are getting confused. Other external clients seem quite happy to give us a PO, since they don't need to look anyone up in Agresso to do so. Uni accounts get confused they can't find TEC, so telling them to use UoNSU on the quote may be a solution (though saying that, I've told them in person and over email before and they've still got confused...).
Something like "Please use Agresso ID XYZ for UoNSU to generate a PO number" would probably work. I don't think it suggests SU Finance are morons, and instead hopefully removes confusion.
To that end, a tick box for "Has University account" will probably be the solution. Perhaps the addition of a space to write a PO would make it clearer that this is essential. University accounts are easy to identify as being anything within the university that isn't the SU.
