### ISSUE TITLE
Event authorisation should automatically set event to booked.

### ISSUE THREAD

**Issue by johnathan99j** [nottinghamtec/PyRIGS#320]

**Comment by harry-bridge** [comment]
@johnathan99j When the authorisation is sent or confirmed by the client?

**Comment by davidtaylorhq** [comment]
@pickleshb Pretty sure it should be once it’s confirmed by the client. This was by design. Why don’t you want it to be marked booked automatically?

**Comment by tomtom5152** [comment]
@davidtaylorhq Close, the original design was deliberately not automatic, as you could confirm the price whilst still uming and arhing about the finer details, at which point you would change the status

**Comment by johnathan99j** [comment]
@pickleshb yes when it's confirmed by the client. @davidtaylorhq I'm a bit confused, I want it to mark them booked when confirmation is received, this currently doesn't happen.

**Comment by davidtaylorhq** [comment]
> I'm a bit confused, I want it to mark them booked when confirmation is received

I read your title as a "bug report" rather than a "feature request" - hence my confusion, and then your confusion 😆 

So the way it actually works now is how @tomtom5152 designed it. I'm not that bothered either way so I guess it's up to you as treasurer if you want 'booked' to happen automatically, unless @tomtom5152 has any strong objections?
