### ISSUE TITLE
Remove AssetID from user control

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#343]
Asset IDs should automatically increment to the next available value - when the 'Add asset' form is opened, the asset ID should be pre-filled with this value rather than user editable.

If an asset of a specific ID needs to be added (e.g. we found something in the storeroom that's not in the database) this should be done through the admin panel.

**Comment by harry-bridge** [comment]
Disagree with this, we're all adults here, it should ideally autofill with the right asset id number but it should be able to be edited

**Comment by FreneticScribbler** [comment]
Why, what's the benefit?

Apart from the rare case listed above, what situation would one want to assign a custom ID?

**Comment by harry-bridge** [comment]
Well for one we haven't actually decided if we're going to change to a new asset numbering system, so for now checking that the value is unique is enough, can be done by setting unique=True on the model, but the duplicates from the old database need fixing first otherwise editing an old item (if it gets sold or scrapped) could fail due to the unique constraint.

**Comment by FreneticScribbler** [comment]
Oh I was under the impression that decision had been made. (Closing until it is, either way)
