### ISSUE TITLE
Sample data for assets

### ISSUE THREAD

**Issue by FreneticScribbler** [nottinghamtec/PyRIGS#364]
Should be automatically created. 

While we're at it may as well modify deleteSampleData to apply to everything not just assets. I've found it useful.

**Comment by mattysmith22** [comment]
Just curious, what does `deleteSampleData` do that `flush` does not?

**Comment by harry-bridge** [comment]
Yes less destructive, It only deletes the models that the create sample data command populates. I.e it keeps the users, permissions, and anything else you want to keep, so you don't have to faff with all that again. Flush just drops everything apart from migrations

**Comment by mattysmith22** [comment]
Alright, I will look into getting this done. Sample data generation for assets is fixed with commits https://github.com/nottinghamtec/PyRIGS/commit/9495fa2fdba46df3b0b48f7e94197560bbe5f64a and https://github.com/nottinghamtec/PyRIGS/commit/1b12953803541d779bab099bb0466670904875cb. I will get this done once all things that would be nice to have done before release.

**Comment by FreneticScribbler** [comment]
This was fixed a while back, delete is non-critical.
