### ISSUE TITLE
Unable to log session: 494 is not one of the available choices.

### ISSUE THREAD

**Issue by alexdaniel654** [nottinghamtec/PyRIGS#552]
Trying to input what was covered at last nights HNTD but keep getting the error above whenever I try and input the data below. No silly notes in the notes field this time. Annoyingly it clears everything but the supervisor when it goes wrong.

![image](https://github.com/nottinghamtec/PyRIGS/assets/23356429/b580dd47-dd26-45cc-87d9-8a42075599bf)

**Comment by FreneticScribbler** [comment]
> Annoyingly it clears everything but the supervisor when it goes wrong.

Yeah, this is very irritating. Known upstream bug with the 'multi select' doodads. 

Investigating.

**Comment by FreneticScribbler** [comment]
494 references a user that hasn't activated their account, which is probably the issue. Or it's because their account was not approved. In any case, I've approved them and force-activated their account, so you should be able to log this now. 

I don't think I can make it possible to add records for users that are unapproved/unactivated, so I guess I need to ensure they don't show up in the lists.

**Comment by alexdaniel654** [comment]
Cool, I normally wait a bit longer before logging HNTDs, I just saw a nice list of tagged people on the forum and thought I'd do it while I remembered. Yeah if they didn't appear in the list of users that would be great. Alternatively, if its easier to adjust the error message so it's a bit more descriptive e.g. `f"Select a valid user, {username} is not available."` then that would be fine as I'd have known what the issue was and only have to retype everything once.
