### ISSUE TITLE
Allow selection of multiple roles when checking into events

### ISSUE THREAD

**Issue by nickw29** [nottinghamtec/PyRIGS#562]
Allow people to select multiple roles when checking into an event, e.g. MIC and power MIC

**Comment by FreneticScribbler** [comment]
This is already possible. It's a free text field, you can put whatever you like in, for reasons such as this. 

The buttons are there as a shortcut (which incidentally helps keep the data somewhat normalised, as people will generally take the path of least resistance and hit the button rather than enter "MIC" capitalised every different way :P)
